/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const fallbackProjectId = "lypwqqkvvocygfxieppd";
const fallbackPublicAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5cHdxcWt2dm9jeWdmeGllcHBkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAzOTYzODMsImV4cCI6MjA5NTk3MjM4M30.9BjGi018_HfqbHqM5u8FnI9ajxt_OdQhKBRBS_wu8_A";

export const projectId = import.meta.env.VITE_SUPABASE_PROJECT_ID?.trim() || fallbackProjectId;
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY?.trim() || fallbackPublicAnonKey;
