/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

function requireViteEnv(key: "VITE_SUPABASE_PROJECT_ID" | "VITE_SUPABASE_ANON_KEY") {
  const value = import.meta.env[key]?.trim();
  if (!value) {
    throw new Error(`${key} must be configured before running Pathflow.`);
  }

  return value;
}

export const projectId = requireViteEnv("VITE_SUPABASE_PROJECT_ID");
export const publicAnonKey = requireViteEnv("VITE_SUPABASE_ANON_KEY");
